if(NOT DEFINED SOURCE_DIR OR NOT DEFINED DEST_DIR OR NOT DEFINED STAMP_FILE)
    message(FATAL_ERROR "SOURCE_DIR, DEST_DIR, and STAMP_FILE must be set.")
endif()

file(REMOVE_RECURSE "${DEST_DIR}")
file(MAKE_DIRECTORY "${DEST_DIR}")

file(GLOB_RECURSE ROMFS_FILES
    RELATIVE "${SOURCE_DIR}"
    LIST_DIRECTORIES false
    "${SOURCE_DIR}/*"
)
list(SORT ROMFS_FILES)

set(SKIP_PACKED_ATLAS_PAGE_FILES FALSE)
set(PACKED_ATLAS_PATH "${SOURCE_DIR}/gfx/atlas.bin")
if(EXISTS "${PACKED_ATLAS_PATH}")
    file(READ "${PACKED_ATLAS_PATH}" PACKED_ATLAS_VERSION_HEX OFFSET 4 LIMIT 2 HEX)
    if(PACKED_ATLAS_VERSION_HEX STREQUAL "0800")
        set(SKIP_PACKED_ATLAS_PAGE_FILES TRUE)
    endif()
endif()

foreach(REL_PATH IN LISTS ROMFS_FILES)
    if(SKIP_PACKED_ATLAS_PAGE_FILES AND REL_PATH MATCHES "^gfx/page_[0-9][0-9][0-9]\\.(t3x|i8)$")
        continue()
    endif()
    set(SRC_PATH "${SOURCE_DIR}/${REL_PATH}")
    set(DST_PATH "${DEST_DIR}/${REL_PATH}")
    get_filename_component(DST_PARENT "${DST_PATH}" DIRECTORY)
    file(MAKE_DIRECTORY "${DST_PARENT}")
    file(COPY_FILE "${SRC_PATH}" "${DST_PATH}" ONLY_IF_DIFFERENT)
endforeach()

list(LENGTH ROMFS_FILES ROMFS_FILE_COUNT)
file(WRITE "${STAMP_FILE}" "staged ${ROMFS_FILE_COUNT} romfs files\n")
